name: Weekly Update

on:
  schedule:
    # 每周一凌晨2点执行
    - cron: '0 2 * * 1'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Bilibili Hot Videos
    
    permissions:
      # 需要写入权限来推送更改
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.50.0
      
      - name: Install Playwright browsers
        run: playwright install
      
      - name: Run get_list.py
        run: python ./python_script/get_list.py
      
      - name: Run parse_list.py
        run: python ./python_script/parse_list.py
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Commit and push changes
        run: |
          git add -A
          # 如果有更改，则提交并推送
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Weekly update: $(date +'%Y-%m-%d')"
            git push origin main
          fi